"""followers

Revision ID: 206c5fbd0a57
Revises: 46f450cd1d11
Create Date: 2018-03-24 22:46:21.677856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '206c5fbd0a57'
down_revision = '46f450cd1d11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
